CREATE TABLE IF NOT EXISTS Users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
);

CREATE TABLE IF NOT EXISTS PointResults (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE,
  x NUMERIC(5,2) NOT NULL,
  y NUMERIC(5,2) NOT NULL,
  r NUMERIC(5,2) NOT NULL,
  is_hitted BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);